// This file is generated by scripts/import-carl-references.mjs.
// It stores attribution metadata only; displayed C++ remains an independently normalized implementation.

export interface CarlReference {
  pageTitle: string
  url: string
  cppVariants: number
}

export const carlReferences: Readonly<Record<number, CarlReference>> = {
  "1": {
    "pageTitle": "两数之和",
    "url": "https://programmercarl.com/0001.%E4%B8%A4%E6%95%B0%E4%B9%8B%E5%92%8C.html",
    "cppVariants": 1
  },
  "5": {
    "pageTitle": "最长回文子串",
    "url": "https://programmercarl.com/0005.%E6%9C%80%E9%95%BF%E5%9B%9E%E6%96%87%E5%AD%90%E4%B8%B2.html",
    "cppVariants": 7
  },
  "15": {
    "pageTitle": "三数之和",
    "url": "https://programmercarl.com/0015.%E4%B8%89%E6%95%B0%E4%B9%8B%E5%92%8C.html",
    "cppVariants": 5
  },
  "17": {
    "pageTitle": "电话号码的字母组合",
    "url": "https://programmercarl.com/0017.%E7%94%B5%E8%AF%9D%E5%8F%B7%E7%A0%81%E7%9A%84%E5%AD%97%E6%AF%8D%E7%BB%84%E5%90%88.html",
    "cppVariants": 6
  },
  "19": {
    "pageTitle": "删除链表的倒数第N个节点",
    "url": "https://programmercarl.com/0019.%E5%88%A0%E9%99%A4%E9%93%BE%E8%A1%A8%E7%9A%84%E5%80%92%E6%95%B0%E7%AC%ACN%E4%B8%AA%E8%8A%82%E7%82%B9.html",
    "cppVariants": 1
  },
  "20": {
    "pageTitle": "有效的括号",
    "url": "https://programmercarl.com/0020.%E6%9C%89%E6%95%88%E7%9A%84%E6%8B%AC%E5%8F%B7.html",
    "cppVariants": 1
  },
  "24": {
    "pageTitle": "两两交换链表中的节点",
    "url": "https://programmercarl.com/0024.%E4%B8%A4%E4%B8%A4%E4%BA%A4%E6%8D%A2%E9%93%BE%E8%A1%A8%E4%B8%AD%E7%9A%84%E8%8A%82%E7%82%B9.html",
    "cppVariants": 1
  },
  "31": {
    "pageTitle": "下一个排列",
    "url": "https://programmercarl.com/0031.%E4%B8%8B%E4%B8%80%E4%B8%AA%E6%8E%92%E5%88%97.html",
    "cppVariants": 1
  },
  "34": {
    "pageTitle": "在排序数组中查找元素的第一个和最后一个位置",
    "url": "https://programmercarl.com/0034.%E5%9C%A8%E6%8E%92%E5%BA%8F%E6%95%B0%E7%BB%84%E4%B8%AD%E6%9F%A5%E6%89%BE%E5%85%83%E7%B4%A0%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%92%8C%E6%9C%80%E5%90%8E%E4%B8%80%E4%B8%AA%E4%BD%8D%E7%BD%AE.html",
    "cppVariants": 3
  },
  "35": {
    "pageTitle": "搜索插入位置",
    "url": "https://programmercarl.com/0035.%E6%90%9C%E7%B4%A2%E6%8F%92%E5%85%A5%E4%BD%8D%E7%BD%AE.html",
    "cppVariants": 3
  },
  "39": {
    "pageTitle": "组合总和",
    "url": "https://programmercarl.com/0039.%E7%BB%84%E5%90%88%E6%80%BB%E5%92%8C.html",
    "cppVariants": 5
  },
  "42": {
    "pageTitle": "接雨水",
    "url": "https://programmercarl.com/0042.%E6%8E%A5%E9%9B%A8%E6%B0%B4.html",
    "cppVariants": 8
  },
  "45": {
    "pageTitle": "跳跃游戏II",
    "url": "https://programmercarl.com/0045.%E8%B7%B3%E8%B7%83%E6%B8%B8%E6%88%8FII.html",
    "cppVariants": 2
  },
  "46": {
    "pageTitle": "全排列",
    "url": "https://programmercarl.com/0046.%E5%85%A8%E6%8E%92%E5%88%97.html",
    "cppVariants": 4
  },
  "51": {
    "pageTitle": "N皇后",
    "url": "https://programmercarl.com/0051.N%E7%9A%87%E5%90%8E.html",
    "cppVariants": 5
  },
  "53": {
    "pageTitle": "最大子序和",
    "url": "https://programmercarl.com/0053.%E6%9C%80%E5%A4%A7%E5%AD%90%E5%BA%8F%E5%92%8C.html",
    "cppVariants": 3
  },
  "54": {
    "pageTitle": "螺旋矩阵",
    "url": "https://programmercarl.com/0054.%E8%9E%BA%E6%97%8B%E7%9F%A9%E9%98%B5.html",
    "cppVariants": 1
  },
  "55": {
    "pageTitle": "跳跃游戏",
    "url": "https://programmercarl.com/0055.%E8%B7%B3%E8%B7%83%E6%B8%B8%E6%88%8F.html",
    "cppVariants": 1
  },
  "56": {
    "pageTitle": "合并区间",
    "url": "https://programmercarl.com/0056.%E5%90%88%E5%B9%B6%E5%8C%BA%E9%97%B4.html",
    "cppVariants": 1
  },
  "62": {
    "pageTitle": "不同路径",
    "url": "https://programmercarl.com/0062.%E4%B8%8D%E5%90%8C%E8%B7%AF%E5%BE%84.html",
    "cppVariants": 5
  },
  "70": {
    "pageTitle": "爬楼梯",
    "url": "https://programmercarl.com/0070.%E7%88%AC%E6%A5%BC%E6%A2%AF.html",
    "cppVariants": 3
  },
  "72": {
    "pageTitle": "编辑距离",
    "url": "https://programmercarl.com/0072.%E7%BC%96%E8%BE%91%E8%B7%9D%E7%A6%BB.html",
    "cppVariants": 4
  },
  "78": {
    "pageTitle": "子集",
    "url": "https://programmercarl.com/0078.%E5%AD%90%E9%9B%86.html",
    "cppVariants": 3
  },
  "84": {
    "pageTitle": "柱状图中最大的矩形",
    "url": "https://programmercarl.com/0084.%E6%9F%B1%E7%8A%B6%E5%9B%BE%E4%B8%AD%E6%9C%80%E5%A4%A7%E7%9A%84%E7%9F%A9%E5%BD%A2.html",
    "cppVariants": 4
  },
  "98": {
    "pageTitle": "验证二叉搜索树",
    "url": "https://programmercarl.com/0098.%E9%AA%8C%E8%AF%81%E4%BA%8C%E5%8F%89%E6%90%9C%E7%B4%A2%E6%A0%91.html",
    "cppVariants": 10
  },
  "101": {
    "pageTitle": "对称二叉树",
    "url": "https://programmercarl.com/0101.%E5%AF%B9%E7%A7%B0%E4%BA%8C%E5%8F%89%E6%A0%91.html",
    "cppVariants": 6
  },
  "102": {
    "pageTitle": "二叉树的层序遍历",
    "url": "https://programmercarl.com/0102.%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E5%B1%82%E5%BA%8F%E9%81%8D%E5%8E%86.html",
    "cppVariants": 12
  },
  "104": {
    "pageTitle": "二叉树的最大深度",
    "url": "https://programmercarl.com/0104.%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E6%9C%80%E5%A4%A7%E6%B7%B1%E5%BA%A6.html",
    "cppVariants": 10
  },
  "105": {
    "pageTitle": "从前序与中序遍历序列构造二叉树",
    "url": "https://programmercarl.com/0106.%E4%BB%8E%E4%B8%AD%E5%BA%8F%E4%B8%8E%E5%90%8E%E5%BA%8F%E9%81%8D%E5%8E%86%E5%BA%8F%E5%88%97%E6%9E%84%E9%80%A0%E4%BA%8C%E5%8F%89%E6%A0%91.html",
    "cppVariants": 2
  },
  "108": {
    "pageTitle": "将有序数组转换为二叉搜索树",
    "url": "https://programmercarl.com/0108.%E5%B0%86%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84%E8%BD%AC%E6%8D%A2%E4%B8%BA%E4%BA%8C%E5%8F%89%E6%90%9C%E7%B4%A2%E6%A0%91.html",
    "cppVariants": 2
  },
  "121": {
    "pageTitle": "买卖股票的最佳时机",
    "url": "https://programmercarl.com/0121.%E4%B9%B0%E5%8D%96%E8%82%A1%E7%A5%A8%E7%9A%84%E6%9C%80%E4%BD%B3%E6%97%B6%E6%9C%BA.html",
    "cppVariants": 4
  },
  "131": {
    "pageTitle": "分割回文串",
    "url": "https://programmercarl.com/0131.%E5%88%86%E5%89%B2%E5%9B%9E%E6%96%87%E4%B8%B2.html",
    "cppVariants": 7
  },
  "139": {
    "pageTitle": "单词拆分",
    "url": "https://programmercarl.com/0139.%E5%8D%95%E8%AF%8D%E6%8B%86%E5%88%86.html",
    "cppVariants": 4
  },
  "141": {
    "pageTitle": "环形链表",
    "url": "https://programmercarl.com/0141.%E7%8E%AF%E5%BD%A2%E9%93%BE%E8%A1%A8.html",
    "cppVariants": 1
  },
  "142": {
    "pageTitle": "环形链表II",
    "url": "https://programmercarl.com/0142.%E7%8E%AF%E5%BD%A2%E9%93%BE%E8%A1%A8II.html",
    "cppVariants": 1
  },
  "160": {
    "pageTitle": "面试题02.07.链表相交",
    "url": "https://programmercarl.com/%E9%9D%A2%E8%AF%95%E9%A2%9802.07.%E9%93%BE%E8%A1%A8%E7%9B%B8%E4%BA%A4.html",
    "cppVariants": 1
  },
  "189": {
    "pageTitle": "旋转数组",
    "url": "https://programmercarl.com/0189.%E6%97%8B%E8%BD%AC%E6%95%B0%E7%BB%84.html",
    "cppVariants": 1
  },
  "198": {
    "pageTitle": "打家劫舍",
    "url": "https://programmercarl.com/0198.%E6%89%93%E5%AE%B6%E5%8A%AB%E8%88%8D.html",
    "cppVariants": 3
  },
  "199": {
    "pageTitle": "二叉树的右视图",
    "url": "https://programmercarl.com/0102.%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E5%B1%82%E5%BA%8F%E9%81%8D%E5%8E%86.html",
    "cppVariants": 1
  },
  "200": {
    "pageTitle": "岛屿数量.广搜版",
    "url": "https://programmercarl.com/0200.%E5%B2%9B%E5%B1%BF%E6%95%B0%E9%87%8F.%E5%B9%BF%E6%90%9C%E7%89%88.html",
    "cppVariants": 3
  },
  "206": {
    "pageTitle": "翻转链表",
    "url": "https://programmercarl.com/0206.%E7%BF%BB%E8%BD%AC%E9%93%BE%E8%A1%A8.html",
    "cppVariants": 3
  },
  "207": {
    "pageTitle": "课程表",
    "url": "https://programmercarl.com/0207.%E8%AF%BE%E7%A8%8B%E8%A1%A8.html",
    "cppVariants": 1
  },
  "226": {
    "pageTitle": "翻转二叉树",
    "url": "https://programmercarl.com/0226.%E7%BF%BB%E8%BD%AC%E4%BA%8C%E5%8F%89%E6%A0%91.html",
    "cppVariants": 9
  },
  "234": {
    "pageTitle": "回文链表",
    "url": "https://programmercarl.com/0234.%E5%9B%9E%E6%96%87%E9%93%BE%E8%A1%A8.html",
    "cppVariants": 3
  },
  "236": {
    "pageTitle": "二叉树的最近公共祖先",
    "url": "https://programmercarl.com/0236.%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E6%9C%80%E8%BF%91%E5%85%AC%E5%85%B1%E7%A5%96%E5%85%88.html",
    "cppVariants": 9
  },
  "239": {
    "pageTitle": "滑动窗口最大值",
    "url": "https://programmercarl.com/0239.%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3%E6%9C%80%E5%A4%A7%E5%80%BC.html",
    "cppVariants": 4
  },
  "279": {
    "pageTitle": "完全平方数",
    "url": "https://programmercarl.com/0279.%E5%AE%8C%E5%85%A8%E5%B9%B3%E6%96%B9%E6%95%B0.html",
    "cppVariants": 3
  },
  "283": {
    "pageTitle": "移动零",
    "url": "https://programmercarl.com/0283.%E7%A7%BB%E5%8A%A8%E9%9B%B6.html",
    "cppVariants": 1
  },
  "300": {
    "pageTitle": "最长上升子序列",
    "url": "https://programmercarl.com/0300.%E6%9C%80%E9%95%BF%E4%B8%8A%E5%8D%87%E5%AD%90%E5%BA%8F%E5%88%97.html",
    "cppVariants": 2
  },
  "322": {
    "pageTitle": "零钱兑换",
    "url": "https://programmercarl.com/0322.%E9%9B%B6%E9%92%B1%E5%85%91%E6%8D%A2.html",
    "cppVariants": 2
  },
  "347": {
    "pageTitle": "前K个高频元素",
    "url": "https://programmercarl.com/0347.%E5%89%8DK%E4%B8%AA%E9%AB%98%E9%A2%91%E5%85%83%E7%B4%A0.html",
    "cppVariants": 1
  },
  "416": {
    "pageTitle": "分割等和子集",
    "url": "https://programmercarl.com/0416.%E5%88%86%E5%89%B2%E7%AD%89%E5%92%8C%E5%AD%90%E9%9B%86.html",
    "cppVariants": 3
  },
  "739": {
    "pageTitle": "每日温度",
    "url": "https://programmercarl.com/0739.%E6%AF%8F%E6%97%A5%E6%B8%A9%E5%BA%A6.html",
    "cppVariants": 2
  },
  "763": {
    "pageTitle": "划分字母区间",
    "url": "https://programmercarl.com/0763.%E5%88%92%E5%88%86%E5%AD%97%E6%AF%8D%E5%8C%BA%E9%97%B4.html",
    "cppVariants": 2
  },
  "1143": {
    "pageTitle": "最长公共子序列",
    "url": "https://programmercarl.com/1143.%E6%9C%80%E9%95%BF%E5%85%AC%E5%85%B1%E5%AD%90%E5%BA%8F%E5%88%97.html",
    "cppVariants": 2
  }
}
