// Generated by scripts/sync-leetcode-hot100.mjs from LeetCode's public Hot 100 pages.
// Keep this file static at runtime so the visualizer remains a backend-free SPA.
import type { ProblemExample } from './types'

export const officialExamples: Record<number, readonly ProblemExample[]> = {
  "1": [
    {
      "label": "示例 1",
      "input": "nums = [2,7,11,15], target = 9",
      "output": "[0,1]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [3,2,4], target = 6",
      "output": "[1,2]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [3,3], target = 6",
      "output": "[0,1]",
      "source": "leetcode"
    }
  ],
  "2": [
    {
      "label": "示例 1",
      "input": "l1 = [2,4,3], l2 = [5,6,4]",
      "output": "[7,0,8]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "l1 = [0], l2 = [0]",
      "output": "[0]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]",
      "output": "[8,9,9,9,0,0,0,1]",
      "source": "leetcode"
    }
  ],
  "3": [
    {
      "label": "示例 1",
      "input": "s = \"abcabcbb\"",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"bbbbb\"",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"pwwkew\"",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "4": [
    {
      "label": "示例 1",
      "input": "nums1 = [1,3], nums2 = [2]",
      "output": "2.00000",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums1 = [1,2], nums2 = [3,4]",
      "output": "2.50000",
      "source": "leetcode"
    }
  ],
  "5": [
    {
      "label": "示例 1",
      "input": "s = \"babad\"",
      "output": "\"bab\"",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"cbbd\"",
      "output": "\"bb\"",
      "source": "leetcode"
    }
  ],
  "11": [
    {
      "label": "示例 1",
      "input": "[1,8,6,2,5,4,8,3,7]",
      "output": "49",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "height = [1,1]",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "15": [
    {
      "label": "示例 1",
      "input": "nums = [-1,0,1,2,-1,-4]",
      "output": "[[-1,-1,2],[-1,0,1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0,1,1]",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [0,0,0]",
      "output": "[[0,0,0]]",
      "source": "leetcode"
    }
  ],
  "17": [
    {
      "label": "示例 1",
      "input": "digits = \"23\"",
      "output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "digits = \"2\"",
      "output": "[\"a\",\"b\",\"c\"]",
      "source": "leetcode"
    }
  ],
  "19": [
    {
      "label": "示例 1",
      "input": "head = [1,2,3,4,5], n = 2",
      "output": "[1,2,3,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1], n = 1",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = [1,2], n = 1",
      "output": "[1]",
      "source": "leetcode"
    }
  ],
  "20": [
    {
      "label": "示例 1",
      "input": "s = \"()\"",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"()[]{}\"",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"(]\"",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "21": [
    {
      "label": "示例 1",
      "input": "l1 = [1,2,4], l2 = [1,3,4]",
      "output": "[1,1,2,3,4,4]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "l1 = [], l2 = []",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "l1 = [], l2 = [0]",
      "output": "[0]",
      "source": "leetcode"
    }
  ],
  "22": [
    {
      "label": "示例 1",
      "input": "n = 3",
      "output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "n = 1",
      "output": "[\"()\"]",
      "source": "leetcode"
    }
  ],
  "23": [
    {
      "label": "示例 1",
      "input": "lists = [[1,4,5],[1,3,4],[2,6]]",
      "output": "[1,1,2,3,4,4,5,6]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "lists = []",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "lists = [[]]",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "24": [
    {
      "label": "示例 1",
      "input": "head = [1,2,3,4]",
      "output": "[2,1,4,3]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = []",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = [1]",
      "output": "[1]",
      "source": "leetcode"
    }
  ],
  "25": [
    {
      "label": "示例 1",
      "input": "head = [1,2,3,4,5], k = 2",
      "output": "[2,1,4,3,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1,2,3,4,5], k = 3",
      "output": "[3,2,1,4,5]",
      "source": "leetcode"
    }
  ],
  "31": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,3]",
      "output": "[1,3,2]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [3,2,1]",
      "output": "[1,2,3]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1,1,5]",
      "output": "[1,5,1]",
      "source": "leetcode"
    }
  ],
  "32": [
    {
      "label": "示例 1",
      "input": "s = \"(()\"",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \")()())\"",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"\"",
      "output": "0",
      "source": "leetcode"
    }
  ],
  "33": [
    {
      "label": "示例 1",
      "input": "nums = [4,5,6,7,0,1,2], target = 0",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [4,5,6,7,0,1,2], target = 3",
      "output": "-1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1], target = 0",
      "output": "-1",
      "source": "leetcode"
    }
  ],
  "34": [
    {
      "label": "示例 1",
      "input": "nums = [5,7,7,8,8,10], target = 8",
      "output": "[3,4]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [5,7,7,8,8,10], target = 6",
      "output": "[-1,-1]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [], target = 0",
      "output": "[-1,-1]",
      "source": "leetcode"
    }
  ],
  "35": [
    {
      "label": "示例 1",
      "input": "nums = [1,3,5,6], target = 5",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1,3,5,6], target = 2",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1,3,5,6], target = 7",
      "output": "4",
      "source": "leetcode"
    }
  ],
  "39": [
    {
      "label": "示例 1",
      "input": "candidates = [2,3,6,7], target = 7",
      "output": "[[2,2,3],[7]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "candidates = [2,3,5], target = 8",
      "output": "[[2,2,2,2],[2,3,3],[3,5]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "candidates = [2], target = 1",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "41": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,0]",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [3,4,-1,1]",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [7,8,9,11,12]",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "42": [
    {
      "label": "示例 1",
      "input": "height = [0,1,0,2,1,0,1,3,2,1,2,1]",
      "output": "6",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "height = [4,2,0,3,2,5]",
      "output": "9",
      "source": "leetcode"
    }
  ],
  "45": [
    {
      "label": "示例 1",
      "input": "nums = [2,3,1,1,4]",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [2,3,0,1,4]",
      "output": "2",
      "source": "leetcode"
    }
  ],
  "46": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,3]",
      "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0,1]",
      "output": "[[0,1],[1,0]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1]",
      "output": "[[1]]",
      "source": "leetcode"
    }
  ],
  "48": [
    {
      "label": "示例 1",
      "input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]",
      "output": "[[7,4,1],[8,5,2],[9,6,3]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]",
      "output": "[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]",
      "source": "leetcode"
    }
  ],
  "49": [
    {
      "label": "示例 1",
      "input": "strs = [\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]",
      "output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "strs = [\"\"]",
      "output": "[[\"\"]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "strs = [\"a\"]",
      "output": "[[\"a\"]]",
      "source": "leetcode"
    }
  ],
  "51": [
    {
      "label": "示例 1",
      "input": "n = 4",
      "output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "n = 1",
      "output": "[[\"Q\"]]",
      "source": "leetcode"
    }
  ],
  "53": [
    {
      "label": "示例 1",
      "input": "nums = [-2,1,-3,4,-1,2,1,-5,4]",
      "output": "6",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1]",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [5,4,-1,7,8]",
      "output": "23",
      "source": "leetcode"
    }
  ],
  "54": [
    {
      "label": "示例 1",
      "input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]",
      "output": "[1,2,3,6,9,8,7,4,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]",
      "output": "[1,2,3,4,8,12,11,10,9,5,6,7]",
      "source": "leetcode"
    }
  ],
  "55": [
    {
      "label": "示例 1",
      "input": "nums = [2,3,1,1,4]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [3,2,1,0,4]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "56": [
    {
      "label": "示例 1",
      "input": "intervals = [[1,3],[2,6],[8,10],[15,18]]",
      "output": "[[1,6],[8,10],[15,18]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "intervals = [[1,4],[4,5]]",
      "output": "[[1,5]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "intervals = [[4,7],[1,4]]",
      "output": "[[1,7]]",
      "source": "leetcode"
    }
  ],
  "62": [
    {
      "label": "示例 1",
      "input": "m = 3, n = 7",
      "output": "28",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "m = 3, n = 2",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "m = 7, n = 3",
      "output": "28",
      "source": "leetcode"
    }
  ],
  "64": [
    {
      "label": "示例 1",
      "input": "grid = [[1,3,1],[1,5,1],[4,2,1]]",
      "output": "7",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "grid = [[1,2,3],[4,5,6]]",
      "output": "12",
      "source": "leetcode"
    }
  ],
  "70": [
    {
      "label": "示例 1",
      "input": "n = 2",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "n = 3",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "72": [
    {
      "label": "示例 1",
      "input": "word1 = \"horse\", word2 = \"ros\"",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "word1 = \"intention\", word2 = \"execution\"",
      "output": "5",
      "source": "leetcode"
    }
  ],
  "73": [
    {
      "label": "示例 1",
      "input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]",
      "output": "[[1,0,1],[0,0,0],[1,0,1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]",
      "output": "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]",
      "source": "leetcode"
    }
  ],
  "74": [
    {
      "label": "示例 1",
      "input": "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "75": [
    {
      "label": "示例 1",
      "input": "nums = [2,0,2,1,1,0]",
      "output": "[0,0,1,1,2,2]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [2,0,1]",
      "output": "[0,1,2]",
      "source": "leetcode"
    }
  ],
  "76": [
    {
      "label": "示例 1",
      "input": "s = \"ADOBECODEBANC\", t = \"ABC\"",
      "output": "\"BANC\"",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"a\", t = \"a\"",
      "output": "\"a\"",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"a\", t = \"aa\"",
      "output": "\"\"",
      "source": "leetcode"
    }
  ],
  "78": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,3]",
      "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0]",
      "output": "[[],[0]]",
      "source": "leetcode"
    }
  ],
  "79": [
    {
      "label": "示例 1",
      "input": "board = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], word = \"ABCCED\"",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "board = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], word = \"SEE\"",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "board = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], word = \"ABCB\"",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "84": [
    {
      "label": "示例 1",
      "input": "heights = [2,1,5,6,2,3]",
      "output": "10",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "heights = [2,4]",
      "output": "4",
      "source": "leetcode"
    }
  ],
  "94": [
    {
      "label": "示例 1",
      "input": "root = [1,null,2,3]",
      "output": "[1,3,2]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = []",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = [1]",
      "output": "[1]",
      "source": "leetcode"
    }
  ],
  "98": [
    {
      "label": "示例 1",
      "input": "root = [2,1,3]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [5,1,4,null,null,3,6]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "101": [
    {
      "label": "示例 1",
      "input": "root = [1,2,2,3,4,4,3]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [1,2,2,null,3,null,3]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "102": [
    {
      "label": "示例 1",
      "input": "root = [3,9,20,null,null,15,7]",
      "output": "[[3],[9,20],[15,7]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [1]",
      "output": "[[1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = []",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "104": [
    {
      "label": "示例 1",
      "input": "root = [3,9,20,null,null,15,7]",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [1,null,2]",
      "output": "2",
      "source": "leetcode"
    }
  ],
  "105": [
    {
      "label": "示例 1",
      "input": "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]",
      "output": "[3,9,20,null,null,15,7]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "preorder = [-1], inorder = [-1]",
      "output": "[-1]",
      "source": "leetcode"
    }
  ],
  "108": [
    {
      "label": "示例 1",
      "input": "nums = [-10,-3,0,5,9]",
      "output": "[0,-3,9,-10,null,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1,3]",
      "output": "[3,1]",
      "source": "leetcode"
    }
  ],
  "114": [
    {
      "label": "示例 1",
      "input": "root = [1,2,5,3,4,null,6]",
      "output": "[1,null,2,null,3,null,4,null,5,null,6]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = []",
      "output": "[]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = [0]",
      "output": "[0]",
      "source": "leetcode"
    }
  ],
  "118": [
    {
      "label": "示例 1",
      "input": "numRows = 5",
      "output": "[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "numRows = 1",
      "output": "[[1]]",
      "source": "leetcode"
    }
  ],
  "121": [
    {
      "label": "示例 1",
      "input": "[7,1,5,3,6,4]",
      "output": "5",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "prices = [7,6,4,3,1]",
      "output": "0",
      "source": "leetcode"
    }
  ],
  "124": [
    {
      "label": "示例 1",
      "input": "root = [1,2,3]",
      "output": "6",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [-10,9,20,null,null,15,7]",
      "output": "42",
      "source": "leetcode"
    }
  ],
  "128": [
    {
      "label": "示例 1",
      "input": "nums = [100,4,200,1,3,2]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0,3,7,2,5,8,4,6,0,1]",
      "output": "9",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1,0,1,2]",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "131": [
    {
      "label": "示例 1",
      "input": "s = \"aab\"",
      "output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"a\"",
      "output": "[[\"a\"]]",
      "source": "leetcode"
    }
  ],
  "136": [
    {
      "label": "示例 1",
      "input": "nums = [2,2,1]",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [4,1,2,1,2]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1]",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "138": [
    {
      "label": "示例 1",
      "input": "head = [[7,null],[13,0],[11,4],[10,2],[1,0]]",
      "output": "[[7,null],[13,0],[11,4],[10,2],[1,0]]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [[1,1],[2,1]]",
      "output": "[[1,1],[2,1]]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = [[3,null],[3,0],[3,null]]",
      "output": "[[3,null],[3,0],[3,null]]",
      "source": "leetcode"
    }
  ],
  "139": [
    {
      "label": "示例 1",
      "input": "s = \"leetcode\", wordDict = [\"leet\", \"code\"]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"applepenapple\", wordDict = [\"apple\", \"pen\"]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"catsandog\", wordDict = [\"cats\", \"dog\", \"sand\", \"and\", \"cat\"]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "141": [
    {
      "label": "示例 1",
      "input": "head = [3,2,0,-4], pos = 1",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1,2], pos = 0",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = [1], pos = -1",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "142": [
    {
      "label": "示例 1",
      "input": "head = [3,2,0,-4], pos = 1",
      "output": "返回索引为 1 的链表节点",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1,2], pos = 0",
      "output": "返回索引为 0 的链表节点",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = [1], pos = -1",
      "output": "返回 null",
      "source": "leetcode"
    }
  ],
  "146": [
    {
      "label": "示例 1",
      "input": "[\"LRUCache\", \"put\", \"put\", \"get\", \"put\", \"get\", \"put\", \"get\", \"get\", \"get\"]\n[[2], [1, 1], [2, 2], [1], [3, 3], [2], [4, 4], [1], [3], [4]]",
      "output": "[null, null, null, 1, null, -1, null, -1, 3, 4]",
      "source": "leetcode"
    },
    {
      "label": "补充示例 2",
      "input": "[\"LRUCache\",\"put\",\"get\"]\n[[1],[1,1],[1]]",
      "output": "[null,null,1]",
      "source": "supplement"
    },
    {
      "label": "补充示例 3",
      "input": "[\"LRUCache\",\"put\",\"put\",\"get\",\"get\"]\n[[1],[1,1],[2,2],[1],[2]]",
      "output": "[null,null,null,-1,2]",
      "source": "supplement"
    }
  ],
  "148": [
    {
      "label": "示例 1",
      "input": "head = [4,2,1,3]",
      "output": "[1,2,3,4]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [-1,5,3,4,0]",
      "output": "[-1,0,3,4,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = []",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "152": [
    {
      "label": "示例 1",
      "input": "nums = [2,3,-2,4]",
      "output": "6",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [-2,0,-1]",
      "output": "0",
      "source": "leetcode"
    }
  ],
  "153": [
    {
      "label": "示例 1",
      "input": "nums = [3,4,5,1,2]",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [4,5,6,7,0,1,2]",
      "output": "0",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [11,13,15,17]",
      "output": "11",
      "source": "leetcode"
    }
  ],
  "155": [
    {
      "label": "示例 1",
      "input": "[\"MinStack\",\"push\",\"push\",\"push\",\"getMin\",\"pop\",\"top\",\"getMin\"]\n[[],[-2],[0],[-3],[],[],[],[]]",
      "output": "[null,null,null,null,-3,null,0,-2]",
      "source": "leetcode"
    },
    {
      "label": "补充示例 2",
      "input": "[\"MinStack\",\"push\",\"getMin\",\"top\"]\n[[],[5],[],[]]",
      "output": "[null,null,5,5]",
      "source": "supplement"
    },
    {
      "label": "补充示例 3",
      "input": "[\"MinStack\",\"push\",\"push\",\"pop\",\"getMin\"]\n[[],[2],[-1],[],[]]",
      "output": "[null,null,null,null,2]",
      "source": "supplement"
    }
  ],
  "160": [
    {
      "label": "示例 1",
      "input": "intersectVal = 8, listA = [4,1,8,4,5], listB = [5,6,1,8,4,5], skipA = 2, skipB = 3",
      "output": "Intersected at '8'",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "intersectVal = 2, listA = [1,9,1,2,4], listB = [3,2,4], skipA = 3, skipB = 1",
      "output": "Intersected at '2'",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "intersectVal = 0, listA = [2,6,4], listB = [1,5], skipA = 3, skipB = 2",
      "output": "No intersection",
      "source": "leetcode"
    }
  ],
  "169": [
    {
      "label": "示例 1",
      "input": "nums = [3,2,3]",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [2,2,1,1,1,2,2]",
      "output": "2",
      "source": "leetcode"
    }
  ],
  "189": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,3,4,5,6,7], k = 3",
      "output": "[5,6,7,1,2,3,4]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [-1,-100,3,99], k = 2",
      "output": "[3,99,-1,-100]",
      "source": "leetcode"
    }
  ],
  "198": [
    {
      "label": "示例 1",
      "input": "[1,2,3,1]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "[2,7,9,3,1]",
      "output": "12",
      "source": "leetcode"
    }
  ],
  "199": [
    {
      "label": "示例 1",
      "input": "root = [1,2,3,null,5,null,4]",
      "output": "[1,3,4]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [1,2,3,4,null,null,null,5]",
      "output": "[1,3,4,5]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = [1,null,3]",
      "output": "[1,3]",
      "source": "leetcode"
    }
  ],
  "200": [
    {
      "label": "示例 1",
      "input": "grid = [\n  ['1','1','1','1','0'],\n  ['1','1','0','1','0'],\n  ['1','1','0','0','0'],\n  ['0','0','0','0','0']\n]",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "grid = [\n  ['1','1','0','0','0'],\n  ['1','1','0','0','0'],\n  ['0','0','1','0','0'],\n  ['0','0','0','1','1']\n]",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "206": [
    {
      "label": "示例 1",
      "input": "head = [1,2,3,4,5]",
      "output": "[5,4,3,2,1]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1,2]",
      "output": "[2,1]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "head = []",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "207": [
    {
      "label": "示例 1",
      "input": "numCourses = 2, prerequisites = [[1,0]]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "numCourses = 2, prerequisites = [[1,0],[0,1]]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "208": [
    {
      "label": "示例 1",
      "input": "[\"Trie\", \"insert\", \"search\", \"search\", \"startsWith\", \"insert\", \"search\"]\n[[], [\"apple\"], [\"apple\"], [\"app\"], [\"app\"], [\"app\"], [\"app\"]]",
      "output": "[null, null, true, false, true, null, true]",
      "source": "leetcode"
    },
    {
      "label": "补充示例 2",
      "input": "[\"Trie\",\"insert\",\"search\",\"startsWith\"]\n[[],[\"cat\"],[\"cat\"],[\"ca\"]]",
      "output": "[null,null,true,true]",
      "source": "supplement"
    },
    {
      "label": "补充示例 3",
      "input": "[\"Trie\",\"insert\",\"search\",\"startsWith\"]\n[[],[\"apple\"],[\"app\"],[\"app\"]]",
      "output": "[null,null,false,true]",
      "source": "supplement"
    }
  ],
  "215": [
    {
      "label": "示例 1",
      "input": "[3,2,1,5,6,4], k = 2",
      "output": "5",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "[3,2,3,1,2,4,5,5,6], k = 4",
      "output": "4",
      "source": "leetcode"
    }
  ],
  "226": [
    {
      "label": "示例 1",
      "input": "root = [4,2,7,1,3,6,9]",
      "output": "[4,7,2,9,6,3,1]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [2,1,3]",
      "output": "[2,3,1]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = []",
      "output": "[]",
      "source": "leetcode"
    }
  ],
  "230": [
    {
      "label": "示例 1",
      "input": "root = [3,1,4,null,2], k = 1",
      "output": "1",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [5,3,6,2,4,null,null,1], k = 3",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "234": [
    {
      "label": "示例 1",
      "input": "head = [1,2,2,1]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "head = [1,2]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "236": [
    {
      "label": "示例 1",
      "input": "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4",
      "output": "5",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "root = [1,2], p = 1, q = 2",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "238": [
    {
      "label": "示例 1",
      "input": "nums = [1,2,3,4]",
      "output": "[24,12,8,6]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [-1,1,0,-3,3]",
      "output": "[0,0,9,0,0]",
      "source": "leetcode"
    }
  ],
  "239": [
    {
      "label": "示例 1",
      "input": "nums = [1,3,-1,-3,5,3,6,7], k = 3",
      "output": "[3,3,5,5,6,7]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1], k = 1",
      "output": "[1]",
      "source": "leetcode"
    }
  ],
  "240": [
    {
      "label": "示例 1",
      "input": "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 5",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 20",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "279": [
    {
      "label": "示例 1",
      "input": "n = 12",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "n = 13",
      "output": "2",
      "source": "leetcode"
    }
  ],
  "283": [
    {
      "label": "示例 1",
      "input": "nums = [0,1,0,3,12]",
      "output": "[1,3,12,0,0]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0]",
      "output": "[0]",
      "source": "leetcode"
    }
  ],
  "287": [
    {
      "label": "示例 1",
      "input": "nums = [1,3,4,2,2]",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [3,1,3,4,2]",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [3,3,3,3,3]",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "295": [
    {
      "label": "示例 1",
      "input": "[\"MedianFinder\", \"addNum\", \"addNum\", \"findMedian\", \"addNum\", \"findMedian\"]\n[[], [1], [2], [], [3], []]",
      "output": "[null, null, null, 1.5, null, 2.0]",
      "source": "leetcode"
    },
    {
      "label": "补充示例 2",
      "input": "[\"MedianFinder\",\"addNum\",\"findMedian\"]\n[[],[5],[]]",
      "output": "[null,null,5.0]",
      "source": "supplement"
    },
    {
      "label": "补充示例 3",
      "input": "[\"MedianFinder\",\"addNum\",\"addNum\",\"findMedian\"]\n[[],[2],[4],[]]",
      "output": "[null,null,null,3.0]",
      "source": "supplement"
    }
  ],
  "300": [
    {
      "label": "示例 1",
      "input": "nums = [10,9,2,5,3,7,101,18]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [0,1,0,3,2,3]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [7,7,7,7,7,7,7]",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "322": [
    {
      "label": "示例 1",
      "input": "coins = [1, 2, 5], amount = 11",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "coins = [2], amount = 3",
      "output": "-1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "coins = [1], amount = 0",
      "output": "0",
      "source": "leetcode"
    }
  ],
  "347": [
    {
      "label": "示例 1",
      "input": "nums = [1,1,1,2,2,3], k = 2",
      "output": "[1,2]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1], k = 1",
      "output": "[1]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "nums = [1,2,1,2,1,2,3,1,3,2], k = 2",
      "output": "[1,2]",
      "source": "leetcode"
    }
  ],
  "394": [
    {
      "label": "示例 1",
      "input": "s = \"3[a]2[bc]\"",
      "output": "\"aaabcbc\"",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"3[a2[c]]\"",
      "output": "\"accaccacc\"",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "s = \"2[abc]3[cd]ef\"",
      "output": "\"abcabccdcdcdef\"",
      "source": "leetcode"
    }
  ],
  "416": [
    {
      "label": "示例 1",
      "input": "nums = [1,5,11,5]",
      "output": "true",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1,2,3,5]",
      "output": "false",
      "source": "leetcode"
    }
  ],
  "437": [
    {
      "label": "示例 1",
      "input": "root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22",
      "output": "3",
      "source": "leetcode"
    }
  ],
  "438": [
    {
      "label": "示例 1",
      "input": "s = \"cbaebabacd\", p = \"abc\"",
      "output": "[0,6]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"abab\", p = \"ab\"",
      "output": "[0,1,2]",
      "source": "leetcode"
    }
  ],
  "543": [
    {
      "label": "示例 1",
      "input": "root = [1,2,3,4,5]",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "root = [1,2]",
      "output": "1",
      "source": "leetcode"
    }
  ],
  "560": [
    {
      "label": "示例 1",
      "input": "nums = [1,1,1], k = 2",
      "output": "2",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "nums = [1,2,3], k = 3",
      "output": "2",
      "source": "leetcode"
    }
  ],
  "739": [
    {
      "label": "示例 1",
      "input": "temperatures = [73,74,75,71,69,72,76,73]",
      "output": "[1,1,4,2,1,1,0,0]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "temperatures = [30,40,50,60]",
      "output": "[1,1,1,0]",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "temperatures = [30,60,90]",
      "output": "[1,1,0]",
      "source": "leetcode"
    }
  ],
  "763": [
    {
      "label": "示例 1",
      "input": "s = \"ababcbacadefegdehijhklij\"",
      "output": "[9,7,8]",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "s = \"eccbbbbdec\"",
      "output": "[10]",
      "source": "leetcode"
    }
  ],
  "994": [
    {
      "label": "示例 1",
      "input": "grid = [[2,1,1],[1,1,0],[0,1,1]]",
      "output": "4",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "grid = [[2,1,1],[0,1,1],[1,0,1]]",
      "output": "-1",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "grid = [[0,2]]",
      "output": "0",
      "source": "leetcode"
    }
  ],
  "1143": [
    {
      "label": "示例 1",
      "input": "text1 = \"abcde\", text2 = \"ace\"",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 2",
      "input": "text1 = \"abc\", text2 = \"abc\"",
      "output": "3",
      "source": "leetcode"
    },
    {
      "label": "示例 3",
      "input": "text1 = \"abc\", text2 = \"def\"",
      "output": "0",
      "source": "leetcode"
    }
  ]
}
